name: Build Docker Image

on:
  workflow_dispatch:  # 添加手动触发
  push:
    branches:
      - main  # 在 main 分支上的推送触发
    tags:
      - 'v*'  # 推送 tag 时触发
  pull_request:
    branches:
      - main  # PR 到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/vllm
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        timeout-minutes: 1750
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: vllm-base
          cache-from: |
            type=gha
            type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/vllm:main
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          build-args: |
            CUDA_VERSION=12.4.1
            PYTHON_VERSION=3.12
            torch_cuda_arch_list=8.0 8.9+PTX
          outputs: type=registry
          provenance: false

